apiVersion: v1
kind: ConfigMap
metadata:
  name: config-file
data: 
  index.js: |-
    module.exports = () => {
      const data = { rand: [] }
      for (let i = 0; i < {{ .Values.tracerConfig.rowCount }}; i++) {
        data.rand.push({ recorded_timestamp: Date.now(), value: Math.random() })
      }
      return data
    }